### ISSUE TITLE
Default typescript template does not run

### ISSUE THREAD

**Issue by jsharf** [electron-vite/create-electron-vite#37]
```
❯ npm create @quick-start/electron@latest

Need to install the following packages:
@quick-start/create-electron@1.0.23
Ok to proceed? (y) y
✔ Project name: … electron-app
✔ Select a framework: › vanilla
✔ Add TypeScript? … No / Yes
✔ Add Electron updater plugin? … No / Yes
✔ Enable Electron download mirror proxy? … No / Yes

Scaffolding project in /Users/sharf/projects/electron-app...

Done. Now run:

  cd electron-app
  npm install
  npm run dev

❯ cd electron-app
❯ npm install

> electron-app@1.0.0 postinstall
> electron-builder install-app-deps

  • electron-builder  version=24.13.3
  • loaded configuration  file=/Users/sharf/projects/electron-app/electron-builder.yml

added 496 packages, and audited 497 packages in 25s

88 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
❯ npm run dev

> electron-app@1.0.0 dev
> electron-vite dev

failed to load config from /Users/sharf/projects/electron-app/electron.vite.config.ts
error during start dev server and electron app:
TypeError: Cannot redefine property: File
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (/Users/sharf/projects/electron-app/node_modules/@babel/core/lib/index.js:7:8)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Users/sharf/projects/electron-app/node_modules/@babel/core/lib/config/helpers/config-api.js:16:14)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
```

Are there any workarounds to this?

**Comment by jsharf** [comment]
Apologies, looks like I filed this with the wrong project. I was running the command from the documentation:

https://electron-vite.org/guide/#scaffolding-your-first-electron-vite-project
