### ISSUE TITLE
`create-electron-vite` template not work.

### ISSUE THREAD

**Issue by zyyv** [electron-vite/create-electron-vite#7]
- I use `pnpm create electron-vite` create a project
- Then i install there deps on `pnpm i`
- `pnpm run dev`
-  it can't work and following this errors. it seems like `electron` version not correctly.

```
build started...
vite v3.2.4 building for development...

watching for file changes...

build started...
✓ 1 modules transformed.
✓ 1 modules transformed. (x2)
dist-electron/preload/index.js   2.14 KiB / gzip: 0.86 KiB
built in 46ms.
dist-electron/main/index.js   2.33 KiB / gzip: 0.93 KiB
built in 57ms.
/Users/chris/projects/electron-vite-vue/node_modules/.pnpm/electron@21.3.1/node_modules/electron/index.js:17
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again');
          ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/Users/chris/projects/electron-vite-vue/node_modules/.pnpm/electron@21.3.1/node_modules/electron/index.js:17:11)
    at Object.<anonymous> (/Users/chris/projects/electron-vite-vue/node_modules/.pnpm/electron@21.3.1/node_modules/electron/index.js:21:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/chris/projects/electron-vite-vue/node_modules/.pnpm/vite-plugin-electron@0.10.4/node_modules/vite-plugin-electron/index.js:173:90
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Following the console error, `electron@21.3.1`, but in `package.json` is `electron": "^21.1.0"`
I don't know the right version, and i try to upgrade electron verison `^21.1.0` to `^21.3.1`, it also not work.

**Comment by caoxiemeihao** [comment]
Make sure there is a `dist` folder under `node_modules/electron` for the installation to be successful.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/26263658/203881882-05d61997-5cf0-477a-a826-97b04de18a95.png">
